### ISSUE TITLE
Not really an issue- Keeping history

### ISSUE THREAD

**Issue by Dybo007** [s1ntoneli/Copi#1]
Hi, i used to use Maccy, that can keep more than 200 items in the history. I would love to get them two in one app, a secured clipboard app like yours with a large history!! Can you add this feature in the near future please?

Many thanks!

**Comment by s1ntoneli** [comment]
Thanks Dybo,
In fact, I don't plan to do it this way because I am maintaining an app similar to Maccy called [CleanClip](https://cleanclip.cc), which will have the feature of Copi. If Copi also adds a history feature, they will be too similar.

Copi, as a security tool, will continue to develop more in the direction of security.

**Comment by Dybo007** [comment]
Thanks for your answer!!
I understand. And you're right!
Nice apps tho! And nice to see devs to care about privacy!!
Thanks for all!!

**Comment by s1ntoneli** [comment]
Thanks Dybo!
